-- Auto-generated by migrate.ts
-- Database: POSTGRES
-- Generated at: 2025-12-19T17:21:08.124Z

-- Course
CREATE TABLE IF NOT EXISTS courses (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    duration VARCHAR(255),
    lessons NUMERIC(10,2)
);

-- Spu
CREATE TABLE IF NOT EXISTS spus (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    stock BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    brand VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL,
    created_at BIGINT,
    updated_at BIGINT
);

-- User
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);
